#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_INPUT_WIDGET_DIMENSION 1000
#define MIN_INPUT_WIDGET_DIMENSION 100
#define INPUT_WIDGET_DIMENSION_INCREMENTS 100

#define DEFAULT_INPUT_WIDGET_DIMENSION 500

#endif // CONSTANTS_H
