#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_INPUT_WIDGET_DIMENSION 1000
#define MIN_INPUT_WIDGET_DIMENSION 100
#define INPUT_WIDGET_DIMENSION_INCREMENTS 100

#define DEFAULT_INPUT_WIDGET_DIMENSION 500

#define RADIAL_DISTRIBUTION_SUBFOLDER "radial_distribution"
#define CATEGORY_PROPERTIES_SUBFOLDER "category_properties"
#define CSV_FILES_SUBFOLDER "csv"
#define CONFIGURATION_FILE_NAME "configuration.conf"
#define RADIAL_DISTRIBUTION_FILE_EXTENSION ".rad"
#define CATEGORY_PROPERTIES_FILE_EXTENSION ".category_properties"



#endif // CONSTANTS_H
